export const SET_DEVICE = 'SET_DEVICE';

export const SET_APPS = 'SET_APPS';

export const SET_CATEGORIES = 'SET_CATEGORIES';

export const SET_COLLECTIONS = 'SET_COLLECTIONS';

export const FETCH_APPS_FOR_DEVICE = 'FETCH_APPS_FOR_DEVICE';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS';
